### ISSUE TITLE
Python version compatibilty

### ISSUE THREAD

**Issue by rleeden** [avantrec/soco-cli#7]
Hi,

A recent update has caused soco-cli to be incompatible with python version versions lower than 3.7. Documenation still says '**Requires Python 3.5+ for most functions. Python 3.7+ is required for the play_file action.**', but I get following error on my system that is currently stuck on Python 3.6.8:

> root>/bin/python3 --version
> Python 3.6.8
> root>
> root>sonos version
> Traceback (most recent call last):
>   File "/usr/local/bin/sonos", line 5, in <module>
>     from soco_cli.sonos import main
>   File "/usr/local/lib/python3.6/site-packages/soco_cli/sonos.py", line 11, in <module>
>     from .action_processor import list_actions, process_action
>   File "/usr/local/lib/python3.6/site-packages/soco_cli/action_processor.py", line 19, in <module>
>     from .play_local_file import is_supported_type, play_local_file
>   File "/usr/local/lib/python3.6/site-packages/soco_cli/play_local_file.py", line 4, in <module>
>     from http.server import ThreadingHTTPServer
> ImportError: cannot import name 'ThreadingHTTPServer'

Commenting out line 4 in play_local_file.py allows me to run sonos command again, so is it possible to check which version of python is being run, to allow compatibilty for Python lower than 3.7 ?

Thanks :)

**Comment by pwt** [comment]
Yes, sorry about that.

I think I can import a threaded HTTP server in a way that makes it compatible with Python 3.6+. If not, I'll add a version check. I'll take a look at this shortly ... should have a fix today.

**Comment by pwt** [comment]
Version 0.1.51 should fix the issue, and restore overall compatibility back to Python 3.5+.

Now, I know that `play_file` doesn't work on 3.5, and I know it does work on 3.7+, but I don't have a Python 3.6 system at hand ... so, if you get a chance, perhaps you could try it?

**Comment by rleeden** [comment]
Thanks for the very quick fix! Installed latest version (0.1.52) and no errors with Python 3.6.8.

I tried running play_file but that still errors under Python 3.6.8:

root>sonos -l lounge play_file Test.mp3
----------------------------------------
Exception happened during processing of request from ('192.168.0.233', 41456)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/site-packages/soco_cli/play_local_file.py", line 35, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'directory'
----------------------------------------

Not a massive issue for me, as it's not a feature I currently have use for. Plus in the meantime I have managed to get a version of Python 3.7 working on my system, and the above command is working. 

Happy to test again if you need.

**Comment by pwt** [comment]
Thanks for testing. Something changed in in 3.7 in the way that Python handles arguments passed up to a superclass. I'll have a poke around to see if there's an easy way to circumvent it.
